1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

- Llista de publicacions (/posts)
- Llista d’usuaris (/users)
- Llista de tasques (/todos)

In [ ]:
import requests
import pandas as pd

In [ ]:
base_url = "https://jsonplaceholder.typicode.com/"

In [5]:
posts = requests.get(f"{base_url}/posts")
users = requests.get(f"{base_url}/users")
todos = requests.get(f"{base_url}/todos")

2. Cantidad de recursos y código de estado

In [6]:
print("Posts:", len(posts.json()), "Status:", posts.status_code)
print("Users:", len(users.json()), "Status:", users.status_code)
print("Todos:", len(todos.json()), "Status:", todos.status_code)

Posts: 100 Status: 200
Users: 10 Status: 200
Todos: 200 Status: 200

3. Petición a recurso inexistente (404)

In [7]:
error = requests.get(f"{base_url}/posts/9999")
print("Status code error:", error.status_code)

Status code error: 404

4. Petición POST (crear publicación)

In [8]:
nueva_publicacion = {
    "title": "Mi primera publicación API",
    "body": "Este es un mensaje de prueba",
    "userId": 1
}

respuesta_post = requests.post(f"{base_url}/posts", json=nueva_publicacion)

print("JSON respuesta:", respuesta_post.json())
print("Status:", respuesta_post.status_code)

JSON respuesta: {'title': 'Mi primera publicación API', 'body': 'Este es un mensaje de prueba', 'userId': 1, 'id': 101}
Status: 201

5. Petición PATCH (modificar parcialmente)

In [9]:
modificacion = {
    "title": "Título actualizado"
}

respuesta_patch = requests.patch(f"{base_url}/posts/1", json=modificacion)

print("JSON respuesta:", respuesta_patch.json())
print("Status:", respuesta_patch.status_code)

JSON respuesta: {'userId': 1, 'id': 1, 'title': 'Título actualizado', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
Status: 200

6. Petición DELETE

In [10]:
respuesta_delete = requests.delete(f"{base_url}/posts/1")

print("JSON respuesta:", respuesta_delete.json())
print("Status:", respuesta_delete.status_code)

JSON respuesta: {}
Status: 200

NIVEL 2

In [16]:
url1= "https://weatherstack.com/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers"

In [17]:
# Verifica que la respuesta sea en formato JSON (es el más adecuado para este ejercicio)

base_datos_URL2  ="https://weatherstack.com/?utm_source=Github&utm_medium=Referral&utm_campaign=Public-apis-repo-Best-sellers"
respuesta = requests.get(base_datos_URL2)

print(respuesta.headers["Content-Type"])

text/html; charset=UTF-8

In [ ]:
url2  ="http://api.aviationstack.com/v1/flights?access_key=54c5e0c3f5dea0e3555c94ec27667033&limit=5"
respuesta = requests.get(url2)

print(respuesta.headers["Content-Type"])

application/json
application/json

In [20]:
# 3. Haz una petición GET sencilla:
# Muestra el código de estado de la respuesta.
# Imprime de forma clara algunos de los campos de la respuesta JSON.

url2 = "http://api.aviationstack.com/v1/flights?access_key=54c5e0c3f5dea0e3555c94ec27667033&limit=5"

respuesta = requests.get(url2)

# Código de estado
print("Código de estado:", respuesta.status_code)

datos = respuesta.json()

for vuelo in datos["data"]:
    print("Vuelo:", vuelo["flight"]["iata"])
    print("Aerolínea:", vuelo["airline"]["name"])
    print("Estado:", vuelo["flight_status"])
    print()
    print("----------------------")

Código de estado: 200
Vuelo: None
Aerolínea: empty
Estado: active

----------------------
Vuelo: VC
Aerolínea: Voyageur Airways
Estado: scheduled

----------------------
Vuelo: None
Aerolínea: QantasLink
Estado: active

----------------------
Vuelo: None
Aerolínea: QantasLink
Estado: scheduled

----------------------
Vuelo: QG164
Aerolínea: Citilink
Estado: active

----------------------

In [22]:
# 4. Convierte los datos a un DataFrame de pandas:

df = pd.json_normalize(datos["data"])

df.head()

,flight_date,flight_status,live,departure.airport,departure.timezone,departure.iata,departure.icao,departure.terminal,departure.gate,departure.delay,...,airline.iata,airline.icao,flight.number,flight.iata,flight.icao,flight.codeshared,aircraft.registration,aircraft.iata,aircraft.icao,aircraft.icao24
0,2026-03-11,active,None,Toowoomba,Australia/Brisbane,TWB,YTWB,None,None,6.0,...,None,None,None,None,None,None,None,None,None,7C1768
1,2026-03-10,scheduled,None,Malta International,Europe/Malta,MLA,LMML,None,None,NaN,...,VC,VAL,None,VC,VAL,None,None,None,None,C05F00
2,2026-03-10,active,None,Mackay,Australia/Brisbane,MKY,YBMK,None,1,NaN,...,None,QLK,1829,None,QLK1829,None,None,None,None,7C68B1
3,2026-03-10,scheduled,None,Paraburdoo,Australia/Perth,PBO,YPBO,None,None,NaN,...,None,QLK,1623,None,QLK1623,None,None,None,None,7C6844
4,2026-03-10,active,None,Halim Perdana Kusuma,Asia/Jakarta,HLP,WIHH,None,None,NaN,...,QG,CTV,164,QG164,CTV164,None,None,None,None,8A03AC

nivel III

1. Buscar un dataset con package_search y ver detalles con package_show

In [71]:

# Buscar datasets relacionados con accidentes de tráfico
url3 = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_search?q=accidents"

respuesta = requests.get(url3)

print("Código de estado:", respuesta.status_code)

datos = respuesta.json()

# Mostrar algunos datasets encontrados
for dataset in datos["result"]["results"][:10]:
    print("Título:", dataset["title"])
    print("ID:", dataset["id"])
    print("--------------")

Código de estado: 200
Título: Accidents by driver cause managed by the Guàrdia Urbana in the city of Barcelona
ID: 29d1b774-a83e-4c1e-91f7-1b9ad042ea83
--------------
Título: Accidents by mediate cause managed by the Guàrdia Urbana in the city of Barcelona
ID: 719b1054-4166-4692-b63e-622b621b4293
--------------
Título: Accidents  by type managed by the Guàrdia Urbana in the city of Barcelona
ID: 834b8920-0685-4e16-8e20-faf13645f4f3
--------------
Título: People involved in accidents managed by the Police in the city of Barcelona
ID: 87aa433e-fef8-4ff4-8f9a-d66e9beefff6
--------------
Título: Vehicles involved in accidents handled by the police in the city of Barcelona
ID: 317e3743-fb79-4d2f-a128-5f12d2c9a55a
--------------
Título: Accidents managed by the local police in the city of Barcelona
ID: e769eb9d-d778-4cd7-9e3a-5858bba49b20
--------------

2. Obtener detalles del dataset con package_show

In [76]:

url3 = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=accidents-gu-bcn"

respuesta = requests.get(url3)

datos = respuesta.json()

print("Título:", datos["result"]["title"])
print("Número de recursos:", len(datos["result"]["resources"]))

# Mostrar los primeros 3 recursos
for recurso in datos["result"]["resources"][:3]:
    print("Nombre:", recurso["name"])
    print("Formato:", recurso["format"])
    print("Resource ID:", recurso["id"])
    print("-------------")

Título: Accidents managed by the local police in the city of Barcelona
Número de recursos: 22
Nombre: 2025_accidents_gu_bcn.csv
Formato: CSV
Resource ID: 066d46b1-25be-4f08-b0e0-5a233714bda2
-------------
Nombre: 2024_accidents_gu_bcn.csv
Formato: CSV
Resource ID: 66f5e7e3-045b-4d19-b649-2eaea622ae93
-------------
Nombre: 2023_ACCIDENTS_GU_BCN.csv
Formato: CSV
Resource ID: d12c8a6f-feb0-4c3e-bcf1-46b8a8b3d651
-------------

3. Recuperar al menos 100 registros con datastore_search

In [84]:
import requests

url = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/datastore_search"

params = {
    "resource_id": "bd601249-a019-4798-aa3a-f112d4b6845b",
    "limit": 100
}

respuesta = requests.get(url, params=params)

datos = respuesta.json()

records = datos["result"]["records"]

print("Registros:", len(records))

Registros: 100

4. L¿Convertir en dataframe

In [ ]:
df = pd.DataFrame(records)

df.head()

,Num postal caption,Número de vehicles implicats,Nom barri,Coordenada UTM (Y),Número de lesionats greus,Número de lesionats lleus,Nom districte,Descripció tipus dia,NK barri,NK Any,...,Descripció dia setmana,Número de víctimes,Coordenada UTM (X),Mes de any,Dia de setmana,Codi districte,Dia de mes,_id,Hora de dia,Descripció causa vianant
0,Desconegut,2,Desconegut,-1,0,1,Desconegut,Laboral,-1--1--1,2011,...,Dijous,1,-1,1,4,-1,13,1,15,Desconegut
1,Desconegut,1,Desconegut,-1,0,1,Desconegut,Laboral,-1--1--1,2011,...,Dimecres,1,-1,2,3,-1,2,2,11,Desobeir el senyal del semŕfor
2,0189 0189,2,el Camp de l'Arpa del Clot,"4585070,71",0,1,Sant Martí,Laboral,101-10-64,2011,...,Divendres,1,"432021,86",10,5,10,21,3,16,Desconegut
3,0201 0201,2,el Camp de l'Arpa del Clot,"4585164,43",0,1,Sant Martí,Laboral,101-10-64,2011,...,Dilluns,1,"432022,53",11,1,10,14,4,19,Desconegut
4,0275 0277,2,el Camp de l'Arpa del Clot,"4585097,87",0,1,Sant Martí,Laboral,101-10-64,2011,...,Dimarts,1,"431520,25",1,2,10,18,5,12,Desconegut

5. Guarda archivo como csv

In [87]:
df.to_csv("bicing_bcn.csv", index=False)